# Generated by Django 4.0.5 on 2023-01-14 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='avatar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='displayName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='mood',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
