# Generated by Django 4.0.5 on 2023-01-15 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManage', '0002_alter_usermanage_avatar_alter_usermanage_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
