# Generated by Django 4.0.5 on 2023-01-15 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManage', '0003_alter_usermanage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
