# Generated by Django 4.0.5 on 2023-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0005_alter_usermanage_avatar_alter_usermanage_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
