# Generated by Django 4.0.5 on 2023-02-01 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=160, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('displayName', models.CharField(max_length=20, null=True)),
                ('avatar', models.CharField(max_length=30, null=True)),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('mood', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
