# Generated by Django 4.0.5 on 2022-12-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaceroom',
            old_name='name',
            new_name='roomName',
        ),
    ]
