# Generated by Django 4.0.5 on 2022-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0002_rename_name_spaceroom_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceroom',
            name='description',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='spaceroom',
            name='roomName',
            field=models.CharField(max_length=50),
        ),
    ]
