# Generated by Django 4.0.5 on 2022-12-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0004_spaceroom_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceroom',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
