# Generated by Django 4.0.5 on 2022-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0005_spaceroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name=range(1, 11)),
        ),
    ]
