# Generated by Django 4.0.5 on 2022-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0006_alter_spaceroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
