# Generated by Django 4.0.5 on 2022-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0007_alter_spaceroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='spaceroom',
            name='roomName',
            field=models.CharField(error_messages={'blank': 'Cannot be blank'}, max_length=20),
        ),
    ]
