# Generated by Django 4.0.5 on 2022-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0008_alter_spaceroom_description_alter_spaceroom_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='roomName',
            field=models.CharField(max_length=20),
        ),
    ]
