# Generated by Django 4.0.5 on 2023-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0009_alter_spaceroom_roomname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
