# Generated by Django 4.0.5 on 2023-01-07 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpaceRoom', '0010_usersavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavatar',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
