# Generated by Django 4.0.5 on 2023-01-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceRoom', '0011_usersavatar_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAvatar',
        ),
    ]
