# Generated by Django 4.0.5 on 2023-02-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceroom',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
