# Generated by Django 4.1.5 on 2023-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0004_usermanage_currentspaceroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Liker', models.CharField(max_length=1000)),
                ('User', models.CharField(max_length=1000)),
            ],
        ),
    ]
