# Generated by Django 4.0.5 on 2023-03-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Space', '0006_rename_room_message_roomname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='displayName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Space.usermanage'),
        ),
        migrations.AlterField(
            model_name='message',
            name='roomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Space.spaceroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
