# Generated by Django 4.0.5 on 2023-03-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0008_remove_message_id_alter_message_roomname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
