# Generated by Django 4.0.5 on 2023-03-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0009_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_added',
        ),
    ]
