# Generated by Django 4.0.5 on 2023-03-22 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Space', '0010_remove_message_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='roomName',
            new_name='slug',
        ),
    ]
