# Generated by Django 4.0.5 on 2023-03-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0014_alter_chatmessage_content_alter_chatmessage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='displayName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Space.usermanage'),
        ),
    ]
