# Generated by Django 4.0.5 on 2023-03-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0016_remove_chatmessage_displayname_chatmessage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Space.spaceroom'),
        ),
    ]
