# Generated by Django 4.0.5 on 2023-03-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0020_remove_chatmessage_username_chatmessage_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.CharField(max_length=25),
        ),
    ]
