# Generated by Django 4.0.5 on 2023-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0021_alter_chatmessage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
