# Generated by Django 4.0.5 on 2023-03-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0024_alter_chatmessage_displayname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesCount',
        ),
    ]
