# Generated by Django 4.0.5 on 2023-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0025_delete_likescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='mood',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
