# Generated by Django 4.0.5 on 2023-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0026_alter_usermanage_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
