# Generated by Django 4.0.5 on 2023-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0027_alter_chatmessage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRoomManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('capacity', models.IntegerField()),
                ('inRoom', models.IntegerField()),
                ('roomStatus', models.CharField(max_length=5)),
            ],
        ),
    ]
