# Generated by Django 4.0.5 on 2023-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0028_spaceroommanage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpaceRoomManage',
        ),
        migrations.AddField(
            model_name='spaceroom',
            name='inRoom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spaceroom',
            name='roomStatus',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
