# Generated by Django 4.0.5 on 2023-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0031_alter_spaceroom_description_alter_spaceroom_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='spaceroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
