# Generated by Django 4.0.5 on 2023-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0032_alter_chatmessage_slug_alter_spaceroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
