# Generated by Django 4.0.5 on 2023-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0033_alter_spaceroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceroom',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
