# Generated by Django 4.0.5 on 2023-04-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0037_alter_chatmessage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='displayName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Space.usermanage'),
        ),
    ]
