# Generated by Django 4.0.5 on 2023-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0038_alter_chatmessage_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='slug',
            field=models.CharField(max_length=40),
        ),
    ]
