# Generated by Django 4.0.5 on 2023-04-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0040_roommember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
