# Generated by Django 4.0.5 on 2023-04-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0041_delete_roommember'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=20)),
                ('insession', models.BooleanField(default=True)),
            ],
        ),
    ]
